[database]
connection_string = "postgresql://postgres.laukxtwtekcoyuxndina:BookJhenYing07@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres"

[cloudinary]
cloud_name = "dkyxyutyi"
api_key = "814519835841845"
api_secret = "dzLks0SwDB394Yfek8of-vAixq8"