[database]
connection_string = "postgresql://postgres:BookJhenYing07@db.laukxtwtekcoyuxndina.supabase.co:5432/postgres"

[cloudinary]
cloud_name = "dkyxyutyi"
api_key = "814519835841845"
api_secret = "dzLks0SwDB394Yfek8of-vAixq8"